image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  
check:
  stage: test
  script:
    - dotnet build ./PackageDependencies
    - dotnet build ./PackageDependencies
    - dotnet test ./PackageDependencies
    - ls -la ./PackageDependencies/bin/Debug/net6.0/
    - ./PackageDependencies/bin/Debug/net6.0/PackageDependencies

trivy:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
    - ./trivy fs .

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
